title: <p align = "center" Peter Wamburu </p>
logo: "" # your photo (or logo) here
description:
<p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/peter-wamburu/">LinkedIn</a> |
  <a href="https://github.com/pwamburu">GitHub</a>
  </p>
  
  <p align="justify">
  Strategy & Analytics professional with over 5 years experience working in the Finance & Technology spaces in emerging markets. 
  Highly adept at financial modeling, strategic planning and rigorous data analysis using various tool kits (primarily Python, Excel & SQL).
  I particularly enjoy leading and aligning teams to successful outcomes. 
  
  <br><br>
  I am passionate about solving problems through technological innovation. I am currently pursuing a Masters degree in Financial Technology at the University of Glasgow on a highly competitive UK Foreign Commonwealth & Development Office Chevening Award. 
  I also spend time as an Expert at Pariti helping African start-ups raise venture capital by evaluating their investment decks & financial models. 
  My long term objective is to continue building Africa's data capabilities to serve the financially underserved.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-M8Z974NHBS # your Google Analytics tracking ID here
