title: Peter Wamburu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Analytics | Strategy | Finance
  <br><br>
  Life Long Learner
  <br><br>
  <a href="https://www.linkedin.com/in/peter-wamburu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-M8Z974NHBS # your Google Analytics tracking ID here
